export const ALBUMS = {

  'drawings': {
    title: 'Paintings and Drawings',
    preview: 'https://i.imgur.com/08lQQn7.png',
    description: 'Paintings and drawings done since 2017',
    rowHeight: 500,
    images: [
      {src: 'https://i.imgur.com/M5P8i6C.jpg', height: 89, width: 126},
      {src: 'https://i.imgur.com/bWSyOBx.jpg', height: 59, width: 45},
      {src: 'https://i.imgur.com/bzMabf6.jpg', height: 4, width: 3},
      {src: 'https://i.imgur.com/hZA2K3t.jpg', height: 4, width: 3},
      {src: 'https://i.imgur.com/PUvwiKM.jpg', height: 71, width: 63},
      {src: 'https://i.imgur.com/yvQGcxT.jpg', height: 4, width: 3},
      {src: 'https://i.imgur.com/bgjdwzx.jpg', height: 4, width: 3},
      {src: 'https://i.imgur.com/3sHxzow.png', height: 3, width: 4},
      {src: 'https://i.imgur.com/MKUcKe0.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/dLFRUnv.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/eup2xSk.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/QGZLwWt.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/5tocNvt.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/9CPheDY.jpg', height: 64, width: 49},
      {src: 'https://i.imgur.com/SVLOWAh.jpg', height: 4, width: 3},
      {src: 'https://i.imgur.com/gIjwvVg.png', height: 3, width: 4},
      {src: 'https://i.imgur.com/1NnJokx.png', height: 4, width: 3},
      {src: 'https://i.imgur.com/9RivW9I.jpg', height: 4, width: 3},
      {src: 'https://i.imgur.com/cyEtahg.jpg', height: 4, width: 3},
      {src: 'https://i.imgur.com/vm7FUhP.jpg', height: 5, width: 7},
      {src: 'https://i.imgur.com/26ih5iy.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/3quCeuR.jpg', height: 4, width: 3}
    ]
  },

  'miniatures': {
    title: 'Miniature Paintings',
    description: 'D&D miniatures painted with acrylics',
    preview: 'https://i.imgur.com/RWnWg82.png',
    rowHeight: 300,
    images: [
      {src: 'https://i.imgur.com/cQIuKDt.png', height: 3, width: 4},
      {src: 'https://i.imgur.com/bvYbrc7.png', height: 4, width: 3},
      {src: 'https://i.imgur.com/h4pI6IH.png', height: 3, width: 4},
      {src: 'https://i.imgur.com/FlIQJFv.png', height: 3, width: 4},
      {src: 'https://i.imgur.com/L3eZ0YO.png', height: 94, width: 83},
      {src: 'https://i.imgur.com/SPZ8X0i.png', height: 4, width: 3},
      {src: 'https://i.imgur.com/tPv6x38.png', height: 3, width: 4},
      {src: 'https://i.imgur.com/gMmwwks.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/HU6p2DP.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/ffxrdjA.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/WMcrbMB.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/BeOykUI.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/q6MBi4o.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/ZKYPgKG.jpg', height: 3, width: 4},
      {src: 'https://i.imgur.com/smlykM6.jpg', height: 3, width: 4}
    ]
  },

  'illustrator': {
    title: 'Intro to Illustrator',
    description: 'Works done in the course Intro to Illustrator',
    preview: 'https://i.imgur.com/RxJ46jc.png',
    rowHeight: 500,
    images: [
      {src: 'https://i.imgur.com/LYWlVfN.png', height: 29, width: 41},
      {src: 'https://i.imgur.com/9jgDa9q.png', height: 68, width: 95},
      {src: 'https://i.imgur.com/MMLIoxq.png', height: 41, width: 29},
      {src: 'https://i.imgur.com/w6EirNb.png', height: 93, width: 91},
      {src: 'https://i.imgur.com/gpoN6pc.png', height: 52, width: 97},
      {src: 'https://i.imgur.com/lKStuQm.png', height: 1, width: 1},
      {src: 'https://i.imgur.com/74KTAg0.png', height: 41, width: 29}
    ]
  },

  'drawings-old': {
    title: 'Old Drawings',
    description: 'Drawings done around 2010-2014',
    preview: 'https://i.imgur.com/Nm00cXA.png',
    rowHeight: 200,
    images: [
      {src: 'https://i.imgur.com/LGWi5mJ.png', height: 73, width: 94},
      {src: 'https://i.imgur.com/pMMeZco.jpg', height: 83, width: 121},
      {src: 'https://i.imgur.com/CZIuEns.png', height: 25, width: 17},
      {src: 'https://i.imgur.com/tB5afCP.jpg', height: 71, width: 90},
      {src: 'https://i.imgur.com/7E5DJ0m.png', height: 94, width: 71},
      {src: 'https://i.imgur.com/wYDDPom.jpg', height: 51, width: 35},
      {src: 'https://i.imgur.com/8q0fPAr.jpg', height: 4, width: 3},
      {src: 'https://i.imgur.com/tsOTVzV.jpg', height: 4, width: 3},
      {src: 'https://i.imgur.com/7X4yY5W.jpg', height: 4, width: 3},
      {src: 'https://i.imgur.com/kyEVfTq.png', height: 65, width: 64},
      {src: 'https://i.imgur.com/PHgs6Qe.png', height: 53, width: 34},
      {src: 'https://i.imgur.com/ySXzQwk.png', height: 79, width: 56},
      {src: 'https://i.imgur.com/X9FUQU2.png', height: 94, width: 69},
      {src: 'https://i.imgur.com/mbKPXcm.png', height: 39, width: 62},
      {src: 'https://i.imgur.com/I9pmLcu.png', height: 7, width: 5},
      {src: 'https://i.imgur.com/l4XtjHV.png', height: 31, width: 23},
      {src: 'https://i.imgur.com/bkle1XT.png', height: 23, width: 36}
    ]
  },

  'designs-old': {
    title: 'Old Designs',
    description: 'Old style designs ("signatures") done around 2008-2010',
    preview: 'https://i.imgur.com/LMpIjiH.png',
    rowHeight: 100,
    images: [
      {src: 'https://i.imgur.com/98VnOmu.png', height: 32, width: 87},
      {src: 'https://i.imgur.com/tzfwN2L.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/4I4dYTT.png', height: 11, width: 40},
      {src: 'https://i.imgur.com/kBr6qNr.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/RmJjXcF.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/bbHL7wg.png', height: 11, width: 42},
      {src: 'https://i.imgur.com/YvoLsR7.png', height: 1, width: 1},
      {src: 'https://i.imgur.com/fWzvCW6.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/4huW76T.png', height: 8, width: 25},
      {src: 'https://i.imgur.com/vHLKEq9.png', height: 8, width: 25},
      {src: 'https://i.imgur.com/9mNAgRe.png', height: 59, width: 100},
      {src: 'https://i.imgur.com/mV4OKM9.png', height: 8, width: 25},
      {src: 'https://i.imgur.com/ABYUx7F.png', height: 5, width: 13},
      {src: 'https://i.imgur.com/Q2Fk868.png', height: 5, width: 13},
      {src: 'https://i.imgur.com/qLW1yOP.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/uBVaEeT.png', height: 13, width: 45},
      {src: 'https://i.imgur.com/w0UzDuo.png', height: 11, width: 37},
      {src: 'https://i.imgur.com/U8U0Z7U.png', height: 5, width: 18},
      {src: 'https://i.imgur.com/9YxoLWm.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/jjYHvrm.png', height: 25, width: 33},
      {src: 'https://i.imgur.com/eK2GaY3.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/4x5MC4U.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/mKr0k7G.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/cZvbmfc.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/OAOFXLq.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/ncE4SZF.png', height: 3, width: 7},
      {src: 'https://i.imgur.com/r7NsUE7.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/tAOMJC4.png', height: 18, width: 77},
      {src: 'https://i.imgur.com/t9zKd8R.png', height: 5, width: 17},
      {src: 'https://i.imgur.com/Y6eASIg.png', height: 6, width: 25},
      {src: 'https://i.imgur.com/iP9p6fk.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/cE7aJIS.png', height: 8, width: 25},
      {src: 'https://i.imgur.com/xnLmN1S.png', height: 64, width: 205},
      {src: 'https://i.imgur.com/DGR3OIj.png', height: 23, width: 66},
      {src: 'https://i.imgur.com/jqA4FSc.png', height: 8, width: 25},
      {src: 'https://i.imgur.com/Vbhogbo.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/1QAuy6M.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/0S6U7Ga.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/jsphmuG.png', height: 11, width: 37},
      {src: 'https://i.imgur.com/qpMCiBd.png', height: 27, width: 80},
      {src: 'https://i.imgur.com/1qaopZK.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/uGgtboi.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/uSSkW2E.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/jZ6FxOq.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/2E099Dr.png', height: 15, width: 32},
      {src: 'https://i.imgur.com/e26M9Te.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/zJJjkpx.png', height: 98, width: 355},
      {src: 'https://i.imgur.com/g89YyFP.png', height: 98, width: 355},
      {src: 'https://i.imgur.com/HwHf9G8.png', height: 17, width: 40},
      {src: 'https://i.imgur.com/XIsLfHE.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/qf9BppC.png', height: 100, width: 357},
      {src: 'https://i.imgur.com/91tFF2w.png', height: 100, width: 357},
      {src: 'https://i.imgur.com/Cirgnd7.png', height: 2, width: 7},
      {src: 'https://i.imgur.com/WV4mtiW.png', height: 2, width: 3},
      {src: 'https://i.imgur.com/ryPZRkq.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/RzcHyZP.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/rCiejz2.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/3RGyLAD.png', height: 10, width: 39},
      {src: 'https://i.imgur.com/htywSur.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/EO3iCjY.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/iXVOge5.png', height: 20, width: 71},
      {src: 'https://i.imgur.com/74jB9yA.png', height: 57, width: 58},
      {src: 'https://i.imgur.com/aID4v0Y.png', height: 25, width: 72},
      {src: 'https://i.imgur.com/vGwAmyP.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/t6HFJKO.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/IhodABp.png', height: 11, width: 35},
      {src: 'https://i.imgur.com/x7eXpeE.png', height: 11, width: 35},
      {src: 'https://i.imgur.com/iJDvfrJ.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/93bzAcw.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/6FP4Xyo.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/8vM6aWZ.png', height: 67, width: 263},
      {src: 'https://i.imgur.com/KTuqXgX.png', height: 3, width: 7},
      {src: 'https://i.imgur.com/2MS0hhg.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/MdWV8W0.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/pY0m7B7.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/fTs5tCD.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/Yh80xEX.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/8O3WUEC.png', height: 91, width: 62},
      {src: 'https://i.imgur.com/HmwioN5.png', height: 5, width: 19},
      {src: 'https://i.imgur.com/j52RlDB.png', height: 4, width: 11},
      {src: 'https://i.imgur.com/PheYHvS.png', height: 91, width: 62},
      {src: 'https://i.imgur.com/VlSaAZR.png', height: 91, width: 62},
      {src: 'https://i.imgur.com/KvZ9sPl.png', height: 92, width: 317},
      {src: 'https://i.imgur.com/egZhXoU.png', height: 10, width: 39},
      {src: 'https://i.imgur.com/D2qYVrj.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/gYrhxoF.png', height: 38, width: 61},
      {src: 'https://i.imgur.com/Ej3hLqu.png', height: 10, width: 41},
      {src: 'https://i.imgur.com/8hHjNBP.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/zri4DFI.png', height: 8, width: 25},
      {src: 'https://i.imgur.com/rLKxToH.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/6lv4POX.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/7Xr4er5.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/mvf0dtT.png', height: 13, width: 35},
      {src: 'https://i.imgur.com/rX4QDOG.png', height: 11, width: 40},
      {src: 'https://i.imgur.com/DwVQ2dV.png', height: 13, width: 35},
      {src: 'https://i.imgur.com/qrGtSzv.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/n1D11Ss.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/AsrErXV.png', height: 23, width: 79},
      {src: 'https://i.imgur.com/oq66pYK.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/HspKlTO.png', height: 51, width: 190},
      {src: 'https://i.imgur.com/qXzY5oz.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/v1PsAdf.png', height: 37, width: 100},
      {src: 'https://i.imgur.com/VKvoC1w.png', height: 3, width: 10},
      {src: 'https://i.imgur.com/Ph71tmx.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/7IZ3kOG.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/4wLLzHA.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/SOL8CAX.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/618k4FZ.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/giRHMhs.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/ZAZBvuM.png', height: 75, width: 134},
      {src: 'https://i.imgur.com/f3iCBHM.png', height: 9, width: 40},
      {src: 'https://i.imgur.com/ppIr89e.png', height: 13, width: 35},
      {src: 'https://i.imgur.com/y8YdFN6.png', height: 6, width: 25},
      {src: 'https://i.imgur.com/QeD3FDc.png', height: 7, width: 19},
      {src: 'https://i.imgur.com/TTA40pB.png', height: 11, width: 38},
      {src: 'https://i.imgur.com/kc4h45d.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/F6TP5Nl.png', height: 13, width: 35},
      {src: 'https://i.imgur.com/9eYNmdg.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/xZPIhVT.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/FZAsGdM.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/LVUDm8i.png', height: 95, width: 394},
      {src: 'https://i.imgur.com/xbIgOc8.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/BOQJVlO.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/3vRSl3M.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/mvLMW5f.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/pqYvUOi.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/pryMyqG.png', height: 95, width: 364},
      {src: 'https://i.imgur.com/O9tYMTA.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/vqnHlNy.png', height: 1, width: 1},
      {src: 'https://i.imgur.com/3KpAP9H.png', height: 1, width: 5},
      {src: 'https://i.imgur.com/P7NpYuG.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/TuM9881.png', height: 89, width: 160},
      {src: 'https://i.imgur.com/9IDU5dt.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/8Uk5nxx.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/DCfDCCX.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/HSjEYcD.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/uPfqf87.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/Jdx15zh.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/09ef4je.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/3yeQZLd.png', height: 17, width: 76},
      {src: 'https://i.imgur.com/8vYeTYU.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/45fpSf1.png', height: 99, width: 80},
      {src: 'https://i.imgur.com/4UWma8H.png', height: 19, width: 77},
      {src: 'https://i.imgur.com/JSCFQwL.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/pBAVNLn.png', height: 3, width: 5},
      {src: 'https://i.imgur.com/pSXwju6.png', height: 1, width: 1},
      {src: 'https://i.imgur.com/hMQ53oZ.png', height: 17, width: 40},
      {src: 'https://i.imgur.com/Xo8ZdZe.png', height: 11, width: 38},
      {src: 'https://i.imgur.com/QPotRFW.png', height: 18, width: 73},
      {src: 'https://i.imgur.com/GReeFc9.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/bQsJP8o.png', height: 3, width: 4},
      {src: 'https://i.imgur.com/VpnaTC8.png', height: 13, width: 35},
      {src: 'https://i.imgur.com/AuX7KjM.png', height: 30, width: 73},
      {src: 'https://i.imgur.com/t4gxOfU.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/WfTCUXw.png', height: 18, width: 77},
      {src: 'https://i.imgur.com/vJwuKGd.png', height: 6, width: 19},
      {src: 'https://i.imgur.com/iGx1Zj9.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/Km0rO98.png', height: 2, width: 5},
      {src: 'https://i.imgur.com/O618WOQ.png', height: 12, width: 41},
      {src: 'https://i.imgur.com/7IJWyLw.png', height: 70, width: 71},
      {src: 'https://i.imgur.com/7yP9EQS.png', height: 3, width: 10},
      {src: 'https://i.imgur.com/j9L0EBR.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/4z07Xrs.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/o2x85Zw.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/DzmCPtw.png', height: 1, width: 4},
      {src: 'https://i.imgur.com/1ifHDf4.png', height: 11, width: 40}
    ]
  }
};
